name: releases
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  generatesite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
            python-version: '3.x'
      - name: Generate site
        run: make web
      - name: commit pages
        run: |
          git add .
          if git diff-index --quiet HEAD --; then
            echo "No updates found"
          else
            echo "Updates found"
            git config user.name github-actions
            git config user.email github-actions@github.com
            git commit -m "updated at `date`"
            git push
          fi
